var searchData=
[
  ['davidson_2dband_2dratio_4334',['davidson-band-ratio',['../CommandDavidsonBandRatio.html',1,'CommandIndex']]],
  ['debug_4335',['debug',['../CommandDebug.html',1,'CommandIndex']]],
  ['defect_2dsupercell_4336',['defect-supercell',['../CommandDefectSupercell.html',1,'CommandIndex']]],
  ['defects_4337',['Defects',['../DefectTutorials.html',1,'Tutorials']]],
  ['defects_20at_20surfaces_4338',['Defects at surfaces',['../SurfaceDefects.html',1,'DefectTutorials']]],
  ['defects_20in_202d_20materials_4339',['Defects in 2D materials',['../Defects2D.html',1,'DefectTutorials']]],
  ['defects_20in_203d_20materials_4340',['Defects in 3D materials',['../BulkDefects.html',1,'DefectTutorials']]],
  ['density_20of_20states_4341',['Density of states',['../DensityOfStates.html',1,'SolidTutorials']]],
  ['density_2dof_2dstates_4342',['density-of-states',['../CommandDensityOfStates.html',1,'CommandIndex']]],
  ['dependencies_4343',['Dependencies',['../Dependencies.html',1,'Compiling']]],
  ['developer_27s_20guide_4344',['Developer&apos;s Guide',['../DevGuide.html',1,'']]],
  ['dft_20_2b_20u_4345',['DFT + U',['../DFTplusU.html',1,'SolidTutorials']]],
  ['dielectric_20tensor_4346',['Dielectric Tensor',['../DielectricTensor.html',1,'SolidTutorials']]],
  ['direct_20transitions_4347',['Direct transitions',['../DirectTransitions.html',1,'WannierTutorials']]],
  ['dispersion_20_28vdw_29_20corrections_4348',['Dispersion (vdW) corrections',['../Dispersion.html',1,'SolidTutorials']]],
  ['dryruntopdb_4349',['dryRunToPDB',['../dryRunToPDB.html',1,'Visualization_and_post-processing']]],
  ['dump_4350',['dump',['../CommandDump.html',1,'CommandIndex']]],
  ['dump_2deresolved_2ddensity_4351',['dump-Eresolved-density',['../CommandDumpEresolvedDensity.html',1,'CommandIndex']]],
  ['dump_2dfermi_2ddensity_4352',['dump-fermi-density',['../CommandDumpFermiDensity.html',1,'CommandIndex']]],
  ['dump_2dinterval_4353',['dump-interval',['../CommandDumpInterval.html',1,'CommandIndex']]],
  ['dump_2dname_4354',['dump-name',['../CommandDumpName.html',1,'CommandIndex']]],
  ['dump_2donly_4355',['dump-only',['../CommandDumpOnly.html',1,'CommandIndex']]]
];
