var searchData=
[
  ['davidson_2dband_2dratio_4281',['davidson-band-ratio',['../CommandDavidsonBandRatio.html',1,'CommandIndex']]],
  ['debug_4282',['debug',['../CommandDebug.html',1,'CommandIndex']]],
  ['defect_2dsupercell_4283',['defect-supercell',['../CommandDefectSupercell.html',1,'CommandIndex']]],
  ['defects_4284',['Defects',['../DefectTutorials.html',1,'Tutorials']]],
  ['defects_20at_20surfaces_4285',['Defects at surfaces',['../SurfaceDefects.html',1,'DefectTutorials']]],
  ['defects_20in_202d_20materials_4286',['Defects in 2D materials',['../Defects2D.html',1,'DefectTutorials']]],
  ['defects_20in_203d_20materials_4287',['Defects in 3D materials',['../BulkDefects.html',1,'DefectTutorials']]],
  ['density_20of_20states_4288',['Density of states',['../DensityOfStates.html',1,'SolidTutorials']]],
  ['density_2dof_2dstates_4289',['density-of-states',['../CommandDensityOfStates.html',1,'CommandIndex']]],
  ['dependencies_4290',['Dependencies',['../Dependencies.html',1,'Compiling']]],
  ['developer_27s_20guide_4291',['Developer&apos;s Guide',['../DevGuide.html',1,'']]],
  ['dft_20_2b_20u_4292',['DFT + U',['../DFTplusU.html',1,'SolidTutorials']]],
  ['dielectric_20tensor_4293',['Dielectric Tensor',['../DielectricTensor.html',1,'SolidTutorials']]],
  ['direct_20transitions_4294',['Direct transitions',['../DirectTransitions.html',1,'WannierTutorials']]],
  ['dispersion_20_28vdw_29_20corrections_4295',['Dispersion (vdW) corrections',['../Dispersion.html',1,'SolidTutorials']]],
  ['dryruntopdb_4296',['dryRunToPDB',['../dryRunToPDB.html',1,'Visualization_and_post-processing']]],
  ['dump_4297',['dump',['../CommandDump.html',1,'CommandIndex']]],
  ['dump_2deresolved_2ddensity_4298',['dump-Eresolved-density',['../CommandDumpEresolvedDensity.html',1,'CommandIndex']]],
  ['dump_2dfermi_2ddensity_4299',['dump-fermi-density',['../CommandDumpFermiDensity.html',1,'CommandIndex']]],
  ['dump_2dinterval_4300',['dump-interval',['../CommandDumpInterval.html',1,'CommandIndex']]],
  ['dump_2dname_4301',['dump-name',['../CommandDumpName.html',1,'CommandIndex']]],
  ['dump_2donly_4302',['dump-only',['../CommandDumpOnly.html',1,'CommandIndex']]]
];
