var searchData=
[
  ['pcm_2dnonlinear_2ddebug_4374',['pcm-nonlinear-debug',['../CommandPcmNonlinearDebug.html',1,'CommandIndex']]],
  ['pcm_2dnonlinear_2dscf_4375',['pcm-nonlinear-scf',['../CommandPcmNonlinearScf.html',1,'CommandIndex']]],
  ['pcm_2dparams_4376',['pcm-params',['../CommandPcmParams.html',1,'CommandIndex']]],
  ['pcm_2dvariant_4377',['pcm-variant',['../CommandPcmVariant.html',1,'CommandIndex']]],
  ['perturb_2delectric_2dfield_4378',['perturb-electric-field',['../CommandPerturbElectricField.html',1,'CommandIndex']]],
  ['perturb_2dincommensurate_2dwavefunctions_4379',['perturb-incommensurate-wavefunctions',['../CommandPerturbIncommensurateWavefunctions.html',1,'CommandIndex']]],
  ['perturb_2dion_4380',['perturb-ion',['../CommandPerturbIon.html',1,'CommandIndex']]],
  ['perturb_2dminimize_4381',['perturb-minimize',['../CommandPerturbMinimize.html',1,'CommandIndex']]],
  ['perturb_2drhoexternal_4382',['perturb-rhoExternal',['../CommandPerturbRhoExternal.html',1,'CommandIndex']]],
  ['perturb_2dtest_4383',['perturb-test',['../CommandPerturbTest.html',1,'CommandIndex']]],
  ['perturb_2dvexternal_4384',['perturb-Vexternal',['../CommandPerturbVexternal.html',1,'CommandIndex']]],
  ['perturb_2dwavevector_4385',['perturb-wavevector',['../CommandPerturbWavevector.html',1,'CommandIndex']]],
  ['phonon_4386',['phonon',['../CommandPhonon.html',1,'CommandIndex']]],
  ['phonon_20dispersion_4387',['Phonon dispersion',['../PhononDispersion.html',1,'PhononTutorials']]],
  ['phonons_4388',['Phonons',['../PhononTutorials.html',1,'Tutorials']]],
  ['plotconvergence_4389',['plotConvergence',['../plotConvergence.html',1,'Output_examination_and_debugging']]],
  ['polarizability_4390',['polarizability',['../CommandPolarizability.html',1,'CommandIndex']]],
  ['polarizability_2dkdiff_4391',['polarizability-kdiff',['../CommandPolarizabilityKdiff.html',1,'CommandIndex']]],
  ['potential_2dsubtraction_4392',['potential-subtraction',['../CommandPotentialSubtraction.html',1,'CommandIndex']]],
  ['practical_20dft_20mini_2dcourse_4393',['Practical DFT mini-course',['../PracticalDFT.html',1,'Resources']]],
  ['prerequisites_4394',['Prerequisites',['../Prerequisites.html',1,'Compiling']]],
  ['printstacktrace_4395',['printStackTrace',['../printStackTrace.html',1,'Output_examination_and_debugging']]],
  ['pseudopotentials_4396',['Pseudopotentials',['../Pseudopotentials.html',1,'Resources']]],
  ['pt_28100_29_20setup_4397',['Pt(100) setup',['../Pt100.html',1,'MetalSurfaces']]],
  ['pt_28110_29_20setup_4398',['Pt(110) setup',['../Pt110.html',1,'MetalSurfaces']]],
  ['pt_28111_29_20setup_4399',['Pt(111) setup',['../Pt111.html',1,'MetalSurfaces']]]
];
