var searchData=
[
  ['pcm_2dnonlinear_2ddebug_4382',['pcm-nonlinear-debug',['../CommandPcmNonlinearDebug.html',1,'CommandIndex']]],
  ['pcm_2dnonlinear_2dscf_4383',['pcm-nonlinear-scf',['../CommandPcmNonlinearScf.html',1,'CommandIndex']]],
  ['pcm_2dparams_4384',['pcm-params',['../CommandPcmParams.html',1,'CommandIndex']]],
  ['pcm_2dvariant_4385',['pcm-variant',['../CommandPcmVariant.html',1,'CommandIndex']]],
  ['perturb_2delectric_2dfield_4386',['perturb-electric-field',['../CommandPerturbElectricField.html',1,'CommandIndex']]],
  ['perturb_2dincommensurate_2dwavefunctions_4387',['perturb-incommensurate-wavefunctions',['../CommandPerturbIncommensurateWavefunctions.html',1,'CommandIndex']]],
  ['perturb_2dion_4388',['perturb-ion',['../CommandPerturbIon.html',1,'CommandIndex']]],
  ['perturb_2dminimize_4389',['perturb-minimize',['../CommandPerturbMinimize.html',1,'CommandIndex']]],
  ['perturb_2drhoexternal_4390',['perturb-rhoExternal',['../CommandPerturbRhoExternal.html',1,'CommandIndex']]],
  ['perturb_2dtest_4391',['perturb-test',['../CommandPerturbTest.html',1,'CommandIndex']]],
  ['perturb_2dvexternal_4392',['perturb-Vexternal',['../CommandPerturbVexternal.html',1,'CommandIndex']]],
  ['perturb_2dwavevector_4393',['perturb-wavevector',['../CommandPerturbWavevector.html',1,'CommandIndex']]],
  ['phonon_4394',['phonon',['../CommandPhonon.html',1,'CommandIndex']]],
  ['phonon_20dispersion_4395',['Phonon dispersion',['../PhononDispersion.html',1,'PhononTutorials']]],
  ['phonons_4396',['Phonons',['../PhononTutorials.html',1,'Tutorials']]],
  ['plotconvergence_4397',['plotConvergence',['../plotConvergence.html',1,'Output_examination_and_debugging']]],
  ['polarizability_4398',['polarizability',['../CommandPolarizability.html',1,'CommandIndex']]],
  ['polarizability_2dkdiff_4399',['polarizability-kdiff',['../CommandPolarizabilityKdiff.html',1,'CommandIndex']]],
  ['potential_2dsubtraction_4400',['potential-subtraction',['../CommandPotentialSubtraction.html',1,'CommandIndex']]],
  ['practical_20dft_20mini_2dcourse_4401',['Practical DFT mini-course',['../PracticalDFT.html',1,'Resources']]],
  ['prerequisites_4402',['Prerequisites',['../Prerequisites.html',1,'Compiling']]],
  ['printstacktrace_4403',['printStackTrace',['../printStackTrace.html',1,'Output_examination_and_debugging']]],
  ['pseudopotentials_4404',['Pseudopotentials',['../Pseudopotentials.html',1,'Resources']]],
  ['pt_28100_29_20setup_4405',['Pt(100) setup',['../Pt100.html',1,'MetalSurfaces']]],
  ['pt_28110_29_20setup_4406',['Pt(110) setup',['../Pt110.html',1,'MetalSurfaces']]],
  ['pt_28111_29_20setup_4407',['Pt(111) setup',['../Pt111.html',1,'MetalSurfaces']]]
];
