/*-------------------------------------------------------------------
Copyright 2013 Ravishankar Sundararaman

This file is part of JDFTx.

JDFTx is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JDFTx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JDFTx.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------*/

#include <electronic/symbols.h>

EnumStringMap<AtomicSymbol> atomicSymbolMap
(	AtomicSymbol::H, "H",
	AtomicSymbol::He, "He",
	AtomicSymbol::Li, "Li",
	AtomicSymbol::Be, "Be",
	AtomicSymbol::B, "B",
	AtomicSymbol::C, "C",
	AtomicSymbol::N, "N",
	AtomicSymbol::O, "O",
	AtomicSymbol::F, "F",
	AtomicSymbol::Ne, "Ne",
	AtomicSymbol::Na, "Na",
	AtomicSymbol::Mg, "Mg",
	AtomicSymbol::Al, "Al",
	AtomicSymbol::Si, "Si",
	AtomicSymbol::P, "P",
	AtomicSymbol::S, "S",
	AtomicSymbol::Cl, "Cl",
	AtomicSymbol::Ar, "Ar",
	AtomicSymbol::K, "K",
	AtomicSymbol::Ca, "Ca",
	AtomicSymbol::Sc, "Sc",
	AtomicSymbol::Ti, "Ti",
	AtomicSymbol::V, "V",
	AtomicSymbol::Cr, "Cr",
	AtomicSymbol::Mn, "Mn",
	AtomicSymbol::Fe, "Fe",
	AtomicSymbol::Co, "Co",
	AtomicSymbol::Ni, "Ni",
	AtomicSymbol::Cu, "Cu",
	AtomicSymbol::Zn, "Zn",
	AtomicSymbol::Ga, "Ga",
	AtomicSymbol::Ge, "Ge",
	AtomicSymbol::As, "As",
	AtomicSymbol::Se, "Se",
	AtomicSymbol::Br, "Br",
	AtomicSymbol::Kr, "Kr",
	AtomicSymbol::Rb, "Rb",
	AtomicSymbol::Sr, "Sr",
	AtomicSymbol::Y, "Y",
	AtomicSymbol::Zr, "Zr",
	AtomicSymbol::Nb, "Nb",
	AtomicSymbol::Mo, "Mo",
	AtomicSymbol::Tc, "Tc",
	AtomicSymbol::Ru, "Ru",
	AtomicSymbol::Rh, "Rh",
	AtomicSymbol::Pd, "Pd",
	AtomicSymbol::Ag, "Ag",
	AtomicSymbol::Cd, "Cd",
	AtomicSymbol::In, "In",
	AtomicSymbol::Sn, "Sn",
	AtomicSymbol::Sb, "Sb",
	AtomicSymbol::Te, "Te",
	AtomicSymbol::I, "I",
	AtomicSymbol::Xe, "Xe",
	AtomicSymbol::Cs, "Cs",
	AtomicSymbol::Ba, "Ba",
	AtomicSymbol::La, "La",
	AtomicSymbol::Ce, "Ce",
	AtomicSymbol::Pr, "Pr",
	AtomicSymbol::Nd, "Nd",
	AtomicSymbol::Pm, "Pm",
	AtomicSymbol::Sm, "Sm",
	AtomicSymbol::Eu, "Eu",
	AtomicSymbol::Gd, "Gd",
	AtomicSymbol::Tb, "Tb",
	AtomicSymbol::Dy, "Dy",
	AtomicSymbol::Ho, "Ho",
	AtomicSymbol::Er, "Er",
	AtomicSymbol::Tm, "Tm",
	AtomicSymbol::Yb, "Yb",
	AtomicSymbol::Lu, "Lu",
	AtomicSymbol::Hf, "Hf",
	AtomicSymbol::Ta, "Ta",
	AtomicSymbol::W, "W",
	AtomicSymbol::Re, "Re",
	AtomicSymbol::Os, "Os",
	AtomicSymbol::Ir, "Ir",
	AtomicSymbol::Pt, "Pt",
	AtomicSymbol::Au, "Au",
	AtomicSymbol::Hg, "Hg",
	AtomicSymbol::Tl, "Tl",
	AtomicSymbol::Pb, "Pb",
	AtomicSymbol::Bi, "Bi",
	AtomicSymbol::Po, "Po",
	AtomicSymbol::At, "At",
	AtomicSymbol::Rn, "Rn",
	AtomicSymbol::Fr, "Fr",
	AtomicSymbol::Ra, "Ra",
	AtomicSymbol::Ac, "Ac",
	AtomicSymbol::Th, "Th",
	AtomicSymbol::Pa, "Pa",
	AtomicSymbol::U, "U",
	AtomicSymbol::Np, "Np",
	AtomicSymbol::Pu, "Pu",
	AtomicSymbol::Am, "Am",
	AtomicSymbol::Cm, "Cm",
	AtomicSymbol::Bk, "Bk",
	AtomicSymbol::Cf, "Cf",
	AtomicSymbol::Es, "Es",
	AtomicSymbol::Fm, "Fm",
	AtomicSymbol::Md, "Md",
	AtomicSymbol::No, "No",
	AtomicSymbol::Lr, "Lr",
	AtomicSymbol::Rf, "Rf",
	AtomicSymbol::Db, "Db",
	AtomicSymbol::Sg, "Sg",
	AtomicSymbol::Bh, "Bh",
	AtomicSymbol::Hs, "Hs",
	AtomicSymbol::Mt, "Mt",
	AtomicSymbol::Ds, "Ds",
	AtomicSymbol::Rg, "Rg",
	AtomicSymbol::Cn, "Cn",
	AtomicSymbol::Uut, "Uut",
	AtomicSymbol::Uuq, "Uuq",
	AtomicSymbol::Uup, "Uup",
	AtomicSymbol::Uuh, "Uuh",
	AtomicSymbol::Uus, "Uus",
	AtomicSymbol::Uuo, "Uuo"
);
