/*-------------------------------------------------------------------
Copyright 2013 Ravishankar Sundararaman

This file is part of JDFTx.

JDFTx is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JDFTx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JDFTx.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------*/

#ifndef JDFTX_ELECTRONIC_VIBRATIONS_H
#define JDFTX_ELECTRONIC_VIBRATIONS_H

#include <core/VectorField.h>
#include <electronic/IonicMinimizer.h>
#include <set>

class Everything;


// Structure representing an individual mode
struct Mode
{	unsigned s; //!< species number
	unsigned a; //!< atom number
	vector3<> n; //!< cartesian direction
	bool isPrimary; //!< whether this mode belongs to the irredicuble wedge (false => generated by symmetrization)
	bool fromTranslation; //!< whether this mode is filled in by the translation symmetry
};

// Structure to hold results from computations/analysis for passing to helper functions
struct VibrationsData
{	std::vector<Mode> modes; //!< vibrational modes / degrees of freedom
	int nModes; //!< number of vibrational modes cast to signed integer
	int nPrimary; //!< number of primary modes
	int nConfigs; //!< number of configurations to evaluate 1 + 2*nPrimary for central difference, else 1 + nPrimary
	bool foundTranslatable; //!< whether any of the modes are trans
	std::vector<unsigned> iRotInv; //!< mapping from symmetry operation index to its inverse (for symmetrization)
	std::vector<IonicGradient> ds; //!< ionic gradients for each configuration 
	std::vector<std::vector<int>> iModeToConfigs; //!< mapping from mode index to configuration indices
	matrix K; //!< Hessian matrix
	matrix dP; //!< dipole moment derivative matrix
	diagMatrix mult; //!< multiplicity of each mode (due to symmetries)
	diagMatrix invsqrtM; //!< inverse square root of mass matrix
	matrix omegaSq; //!< frequency-squared matrix
	diagMatrix omegaSqEigs; //!< eigenvalues of frequency-squared matrix
	matrix omegaSqEvecs; //!< eigenvectors of frequency-squared matrix
	int iZeroStart, iRealStart; //!< index of first zero and real mode
	std::set<int> iFreqChange; //!< index of modes whose energy differs (more than resolution) from previous one
};

//! @addtogroup Output
//! @{

//! Vibrational modes and free energy calculator
class Vibrations
{
public:
	double dr; //!< Perturbation amplitude
	bool centralDiff; //!< whether to use central difference derivatives
	bool useConstraints; //!< whether to use ion constraints to restrict vibrational modes
	bool translationSym; //!< whether to use translation symmetry to optimize force calculations
	bool rotationSym; //!< whether to project out rotational modes: valid only for molecules
	double omegaMin; //!< frequency cutoff for free energy calculation and detailed mode print out
	double T; //!< ionic temperature used for entropy and free energy estimation
	double omegaResolution; //!< frequency resolution used for identifying and reporting degeneracies
	bool dumpK; //!< whether to dump the Hessian
	int iConfiguration; //!< index of configuration being evaluated (for checkpointing)
	int nConfigurations; //!< total number of configurations to evaluate (for checkpointing)
	
	Vibrations();
	void setup(Everything* e);
	void calculate();
	
private:
	Everything* e;
	int iConfigStart, iConfigStop; //range of configurations to evaluate
	bool computeOnly; //whether to only compute the configurations, or also collect them into the Hessian and dipole derivative matrices
	vector3<> getSplit() const; //get optimum latttice coordinates for splitting periodicity in a molecular geometry
	struct IonicGradient getCMcoords() const; //get cartesian coordinates of all atoms relative to molecule center of mass
	VectorField Ptest; //vector field that measures dipole moment in lattice coordinates
	vector3<> getPel() const; //get electronic dipole moment at current state in cartesian coordinates
	void construct_modes(VibrationsData& data); //construct vibrational modes and Hessian/dipole derivative matrices
	void construct_maps(VibrationsData& data); //construct mapping from modes to configurations and the corresponding ionic gradients
	void set_iRotInv(VibrationsData& data); //set the inverse of each symmetry operation
	void compute_iConfig(IonicMinimizer& imin, IonicGradient& d, IonicGradient& grad, vector3<>& Pel); //compute the ionic gradient and dipole moment for a given perturbation d
	void compute_or_collect_iConfig(IonicMinimizer& imin, std::vector<IonicGradient>& ds, IonicGradient& grad, vector3<>& Pel, int iConfig); //compute or collect the ionic gradient and dipole moment for a given configuration index
	void process_mode(IonicMinimizer& imin, int iMode, VibrationsData& data, IonicGradient& grad0, vector3<>& Pel0);
	void collect_cur_contributions(VibrationsData& data, const IonicGradient& Kcur, const vector3<>& dPcur, int iMode);
	void account_for_multiplicity(VibrationsData& data); //account for multiplicity of each mode in the Hessian and dipole derivative matrices
	void fill_in_trans_sym_modes(VibrationsData& data); //fill in the translation and rotation modes in the Hessian and dipole derivative matrices
	void apply_projections(VibrationsData& data); //project out translation and rotation modes from the Hessian and dipole derivative matrices
	void solve_modes(VibrationsData& data); //solve the eigenvalue problem for the Hessian and dipole derivative matrices
	void process_solved_modes(VibrationsData& data); //process the solved modes to identify zero and real modes, and their degeneracies
	void print_modes(VibrationsData& data); //print the vibrational modes and their frequencies to the output file
	void print_free_energy(VibrationsData& data); //print the vibrational free energy components to the output file
};

//! @}
#endif //JDFTX_ELECTRONIC_VIBRATIONS_H
