find_path(LIBXC_INCLUDE_DIR xc.h ${LIBXC_PATH} ${LIBXC_PATH}/include /usr/include /usr/local/include /opt/etsf/include)
find_library(LIBXC_LIBRARY NAMES xc PATHS  ${LIBXC_PATH} ${LIBXC_PATH}/lib  ${LIBXC_PATH}/lib64 /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64 /opt/etsf/lib /opt/etsf/lib64)

if(LIBXC_INCLUDE_DIR AND LIBXC_LIBRARY)
	set(LIBXC_FOUND TRUE)
endif()


if(LIBXC_FOUND)
	if(NOT LIBXC_FIND_QUIETLY)
		message(STATUS "Found LibXC: ${LIBXC_LIBRARY}")
	endif()
else()
	if(LIBXC_FIND_REQUIRED)
		if(NOT LIBXC_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find LibXC headers (Add -D LIBXC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
		if(NOT LIBXC_LIBRARY)
			message(FATAL_ERROR "Could not find LibXC shared libraries (Add -D LIBXC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
	endif()
endif()
