find_path(GSL_INCLUDE_DIR gsl/gsl_math.h /usr/include /usr/local/include)
find_library(GSL_LIBRARY NAMES gsl PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64)

if(GSL_INCLUDE_DIR AND GSL_LIBRARY)
	set(GSL_FOUND TRUE)
endif(GSL_INCLUDE_DIR AND GSL_LIBRARY)


if(GSL_FOUND)
	if(NOT GSL_FIND_QUIETLY)
		message(STATUS "Found GSL: ${GSL_LIBRARY}")
	endif(NOT GSL_FIND_QUIETLY)
else(GSL_FOUND)
	if(GSL_FIND_REQUIRED)
		if(NOT GSL_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find the GNU Scientific Library headers")
		endif(NOT GSL_INCLUDE_DIR)
		if(NOT GSL_LIBRARY)
			MESSAGE(FATAL_ERROR "Could not find the GNU Scientific Library shared libraries")
		endif(NOT GSL_LIBRARY)
	endif(GSL_FIND_REQUIRED)
endif(GSL_FOUND)
