find_path(GSL_INCLUDE_DIR gsl/gsl_cblas.h /usr/include /usr/local/include ${GSL_PATH}/include)
find_library(GSL_LIBRARY NAMES gsl PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64 ${GSL_PATH}/lib)

if(GSL_INCLUDE_DIR AND GSL_LIBRARY)
	set(GSL_FOUND TRUE)
endif()


if(GSL_FOUND)
	if(NOT GSL_FIND_QUIETLY)
		message(STATUS "Found GSL: ${GSL_LIBRARY}")
	endif()
else()
	if(GSL_FIND_REQUIRED)
		if(NOT GSL_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find the GNU Scientific Library headers")
		endif()
		if(NOT GSL_LIBRARY)
			message(FATAL_ERROR "Could not find the GNU Scientific Library shared libraries")
		endif()
	endif()
endif()
